### ISSUE TITLE
[Feature Request] turn display of JSON on/off

### ISSUE THREAD

**Issue by WillFreitag** [tanhauhau/svelte-json-tree#17]
Currently every node has its json-string to the right (sometimes underneath):

![grafik](https://user-images.githubusercontent.com/23337583/180619092-75ecc52a-5f40-4c0d-ba32-0ec7c17b86e2.png)

What about having a switch to enable/disable this?
Something like this:

![grafik](https://user-images.githubusercontent.com/23337583/180619171-a49d4e34-1f1a-4c2a-8bc7-6597d6d8b263.png)

I really believe, that having the JSON displayed is a nice features but there are use cases, where it's more comfortable to read without.

What do you think?

**Comment by tanhauhau** [comment]
This should be fixed in `2.1.0`. Introduced `shouldShowPreview`:

```svelte
<JsonNode {value} shouldShowPreview={false} />
```
