### ISSUE TITLE
"undefined" when passing reference to array element

### ISSUE THREAD

**Issue by brunetton** [tanhauhau/svelte-json-tree#4]
Hi, I'm very happy to find this module that is exactly what I wanted for my project :+1: 

But I run onto an error:

```js
<script>
let value = [true]
let v0 = value[0]
</script>

<JSONTree {v0} />
```

The output is `undefined`

Did I missed something ? 

Thanks !

**Comment by cbenz** [comment]
The component expects a `value` property, not `v0`.

The syntax... 

```
<JSONTree {v0} />
```

... Is a shortcut for

```
<JSONTree v0={v0} />
```

So you should try 

```
<JSONTree value={v0} />
```

You can read about this syntax shortcut in svelte doc.

**Comment by brunetton** [comment]
Thanks @cbenz you're right ! 
This works with `<JSONTree value={v0} />`; closing this issue
