### ISSUE TITLE
Add ability for tree not to be fully condensed by default

### ISSUE THREAD

**Issue by popey456963** [tanhauhau/svelte-json-tree#8]
Sometimes it would be nice to default to expanding, for instance, the first level.

**Comment by FractalHQ** [comment]
In the meantime, does anyone know how to do this manually?

**Comment by tanhauhau** [comment]
with `v1.0.0` you can control which paths / level to be expanded by default:

```svelte
<JsonTree {value} defaultExpandedPaths={['$.a.d.h.1', '$.c.e.*']} />
```

or 


```svelte
<JsonTree {value} defaultExpandedLevel={1} />
```

**Comment by popey456963** [comment]
Woo, thanks so much for this!
